# Dependencies
markdown:         CommonMark
highlighter:      rouge

# Permalinks
permalink:        /:categories/:year/:month/:day/:title/

# Setup
title:            'Deb Pang Davis'
tagline:          'Notebook'
description:      'Design, Technology, Health'
url:              http://dpd28.github.io
baseurl:          /

author:
  name:           'Deb Pang Davis'
  url:            https://twitter.com/yuncod

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dpd28
